"""Turn the captured Felipe frames into watch-ready flipbooks.

Run: python3 export_watch.py   (needs: pip install pillow)
Run it after capturing frames/ from the preview at 15 fps.
Writes watch/felipe.pack (every picture as a JPEG, back to back, which the
watch unpacks with Espressif's esp_new_jpeg) and watch/felipe_frames.h (where
each picture sits and the play order), plus a preview GIF per movement. JPEG
because Felipe's speckled fur defeats lossless squeezing (LZ4, palettes and
frame differences all measured at 5.6-7 MB; JPEG 70 is ~1.4 MB).
"""
from pathlib import Path
import io
from PIL import Image

HERE = Path(__file__).resolve().parent
CAPTURE_FPS = 15
WATCH_FPS = 10                # calibration knob: lower = less storage, choppier
JPEG_QUALITY = 70             # calibration knob: 80 was indistinguishable on the Mac; 70 is smaller
# (first, last, loops) captured frame of each movement, recorded at ?size=330.
# Loop points were found by comparing frames for a clean repeat.
MOVES = {
    'idle': (26, 72, True),             # resting, breathing; 3.1 s
    'paused_intro': (0, 27, False),     # dozes off
    'paused': (28, 57, True),           # asleep with Zzz; 2 s
    'creating_intro': (0, 21, False),   # wakes, easel slides in (connecting)
    'creating': (22, 84, True),         # paints a stroke, then starts again; 4.2 s
    'thinking_intro': (0, 37, False),   # lightbulb switches on
    'thinking': (38, 121, True),        # sway + glowing bulb; 5.6 s (no clean shorter repeat)
    'working_intro': (0, 51, False),    # keyboard appears, starts typing
    'working': (52, 92, True),          # typing; 2.7 s
    'error_intro': (0, 21, False),      # turns red
    'error': (22, 55, True),            # unhappy; 2.3 s
}


def family(name):
    return name.split('_')[0]


def used_box(names):
    """Smallest even-sized area every picture of these movements fits in."""
    box = None
    for name in names:
        first, last, _ = MOVES[name]
        for n in range(first, last + 1):
            a = Image.open(HERE / 'frames' / f"{family(name)}-{n:03d}.png").getchannel('A')
            b = a.point(lambda v: 255 if v > 8 else 0).getbbox()
            if b:
                box = b if box is None else (min(box[0], b[0]), min(box[1], b[1]),
                                             max(box[2], b[2]), max(box[3], b[3]))
    x0, y0, x1, y1 = box
    return (x0, y0, x1 + (x1 - x0) % 2, y1 + (y1 - y0) % 2)


def pad16(box, within):
    """Grow a box to multiples of 16 (the JPEG decoder's block size), staying inside `within`."""
    x0, y0, x1, y1 = box
    w, h = -(-(x1 - x0) // 16) * 16, -(-(y1 - y0) // 16) * 16
    x0 = max(within[0], min(x0, within[2] - w))
    y0 = max(within[1], min(y0, within[3] - h))
    return (x0, y0, x0 + w, y0 + h)


# Each movement is cropped to its own area (a start and its loop share one, so
# they line up); BOX is the area all of them together need on the watch.
BOX = pad16(used_box(list(MOVES)), (0, 0, 10_000, 10_000))
FAMILY_BOX = {f: pad16(used_box([n for n in MOVES if family(n) == f]), BOX) for f in {family(n) for n in MOVES}}


def jpeg(img):
    """One picture as a baseline JPEG, the kind esp_new_jpeg decodes."""
    out = io.BytesIO()
    img.save(out, 'JPEG', quality=JPEG_QUALITY)
    return out.getvalue()


PACK_MAGIC = b'FELIPE01'


def export(name):
    """One movement: its pictures as JPEGs (each stored once) and the play order."""
    first, last, loops = MOVES[name]
    box = FAMILY_BOX[family(name)]
    picked, i = [], 0.0
    while first + round(i) <= last:
        f = Image.open(HERE / 'frames' / f'{family(name)}-{first + round(i):03d}.png').convert('RGBA').crop(box)
        bg = Image.new('RGBA', f.size, 'black')
        bg.alpha_composite(f)
        picked.append(bg.convert('RGB'))
        i += CAPTURE_FPS / WATCH_FPS
    picked[0].save(HERE / 'watch' / f'{name}.gif', save_all=True, append_images=picked[1:],
                   duration=1000 // WATCH_FPS, loop=0)
    # Store each picture once; a still pose just stays up longer.
    seen, pictures, order = {}, [], []
    for im in picked:
        raw = im.tobytes()
        if order and seen.get(raw) == order[-1][0]:
            order[-1][1] += 1
            continue
        if raw not in seen:
            seen[raw] = len(pictures)
            pictures.append(jpeg(im))
        order.append([seen[raw], 1])
    return {'loops': loops, 'x': box[0] - BOX[0], 'y': box[1] - BOX[1],
            'w': box[2] - box[0], 'h': box[3] - box[1], 'pictures': pictures,
            'steps': [(p, n * 1000 // WATCH_FPS) for p, n in order]}


def write_header(moves, offsets, pictures_at):
    """watch/felipe_frames.h: where each picture sits in felipe.pack, and the play order."""
    every = [len(p) for m in moves.values() for p in m['pictures']]
    lines = ['// Generated by firmware/scripts/characters/export_watch.py - do not edit.',
             '#pragma once', '#include <cstdint>', '',
             'namespace felipe {', '',
             f"inline constexpr int kWidth = {BOX[2] - BOX[0]};",
             f"inline constexpr int kHeight = {BOX[3] - BOX[1]};",
             f"inline constexpr uint32_t kBiggestPicture = {max(every)};",
             f"inline constexpr uint32_t kLargestArea = {max(m['w'] * m['h'] for m in moves.values())};",
             f"inline constexpr char kPackMagic[] = \"{PACK_MAGIC.decode()}\";", '',
             'struct Picture { uint32_t start, length; };',
             'struct Step { uint16_t picture, ms; };',
             '// x, y: where this movement sits inside the kWidth x kHeight area.',
             'struct Movement { uint32_t offset; bool loops; uint16_t x, y, w, h; const Picture* pictures; '
             'const Step* steps; uint16_t step_count; };', '']
    for name, m in moves.items():
        pics = ', '.join(f'{{{a}, {b}}}' for a, b in pictures_at[name])
        steps = ', '.join(f'{{{p}, {ms}}}' for p, ms in m['steps'])
        lines += [f'inline constexpr Picture k_{name}_pictures[] = {{{pics}}};',
                  f'inline constexpr Step k_{name}_steps[] = {{{steps}}};']
    lines += ['', 'enum class Move { ' + ', '.join(n.title().replace('_', '') for n in moves) + ', Count };', '',
              'inline constexpr Movement kMovements[] = {']
    for name, m in moves.items():
        lines.append(f'    {{{offsets[name]}, {str(m["loops"]).lower()}, {m["x"]}, {m["y"]}, {m["w"]}, {m["h"]}, '
                     f'k_{name}_pictures, k_{name}_steps, {len(m["steps"])}}},')
    lines += ['};', '', '}  // namespace felipe', '']
    (HERE / 'watch' / 'felipe_frames.h').write_text('\n'.join(lines))


if __name__ == '__main__':
    (HERE / 'watch').mkdir(exist_ok=True)
    moves = {name: export(name) for name in MOVES}
    # felipe.pack: an 8-byte marker, then every movement's JPEGs back to back.
    # The watch reads it a picture at a time from the top 16 MB of flash.
    pack, offsets, pictures_at = bytearray(PACK_MAGIC), {}, {}
    for name, m in moves.items():
        offsets[name], pictures_at[name] = len(pack), []
        for jpg in m['pictures']:
            pictures_at[name].append((len(pack) - offsets[name], len(jpg)))
            pack += jpg
        # self-check: every picture is a JPEG of this movement's own size
        assert m['w'] % 16 == 0 and m['h'] % 16 == 0
        assert m['x'] + m['w'] <= BOX[2] - BOX[0] and m['y'] + m['h'] <= BOX[3] - BOX[1]
        assert all(Image.open(io.BytesIO(j)).size == (m['w'], m['h']) for j in m['pictures'])
        secs = sum(ms for _, ms in m['steps']) / 1000
        print(f"{name:15} {len(m['pictures']):3} pictures  {secs:4.1f} s  {sum(map(len, m['pictures'])) / 1e6:.2f} MB")
    (HERE / 'watch' / 'felipe.pack').write_bytes(bytes(pack))
    write_header(moves, offsets, pictures_at)
    print(f'total {len(pack) / 1e6:.2f} MB')
